### ISSUE TITLE
Lockscreen glitch

### ISSUE THREAD

**Issue by manan001** [aapav01/android_device_samsung_ms013g#2]
many a times lockscreen does not respond properly as a result it freeze the screen. Also found that when disable  broadcast lockscreen works.

**Comment by aapav01** [comment]
Actually every one have there own solution for it
then to i will see what can be done

**Comment by manan001** [comment]
ok do check it..

**Comment by ghost** [comment]
aapav all you need to do is.. just take the old kernel which u packed in re_fix.zip and unpack it.. Then add proper camera blobs from new build and dont make any changes apart from that .. Yureka!! Everything will be stable for everyone 

We are not the only one those who have compiled cm11 from the latest cm11 repo all are facing this lockscreen Lag issue.. even on devices like LG G2 etc etc

**Comment by aapav01** [comment]
hmm.. i will try it later just made a change in a kernel .. will give it to the tester to test it

**Comment by aapav01** [comment]
Fixed
